spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/qtsp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false # host.docker.internal
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorizationserver:8084/oauth2/jwks
          issuer-uri: http://authorizationserver:8084