server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qtsp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  profiles:
    include:
      - "ejbca"
      - "auth"
  application:
    name: qtsp
    version: 0.0.1

info:
  specs: "2.0.0.0"
  name: "remote Qualifies Electronic Signature R3 QTSP"
  logo: "img"
  region: "EU"
  lang: "en-US"
  description: "This is a test Qualified Trust Service Provider"
  authType:
    - "oauth2code"
  oauth2: "http://localhost:9000"
  asynchronousOperationMode: false
  methods:
    - "oauth2/authorize"
    - "oauth2/token"
    - "credentials/list"
    - "credentials/info"
    - "signatures/signHash"
  validationInfo: false
  signAlgorithms:
    algos:
      - "1.2.840.10045.4.3.2"
      - "1.2.840.113549.1.1.1"
      - "1.2.840.113549.1.1.10"
  signature_formats:
    P:
      - "Certification"
      - "Revision"
  conformance_levels:
    - "Ades-B-B"
    - "Ades-B-T"

credentials:
  onlyValidSupport: false

trusted-issuers:
  folder: certificate_of_issuers