server:
  port: 8081

spring:
  application:
    name: qtsp
    version: 0.0.1

info:
  specs: "2.0.0.0"
  name: "remote Qualifies Electronic Signature R3 QTSP"
  logo: "img"
  region: "EU"
  lang: "en-US"
  description: "This is a test Qualified Trust Service Provider"

credentials:
  onlyValidSupport: false