service-url-config:
  oauth2-issuer-url: http://host.docker.internal:8084
  service-url: http://localhost:8084

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/qtsp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false