oauth2-issuer-url:
  url: http://authorizationserver:8084

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/qtsp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver